theme: jekyll-theme-cayman
title: "Sarra BOUHENNI"
subtitle: "PhD candidate @ Université of Claude Bernard, Lyon"
name: "Sarra BOUHENNI"
email: "sarra.bouhenni@liris.cnrs.fr"
address: "Villeurbanne, France"
description: "My research interests include Distributed Graph Algorithms and Big Data."
github:
  is_project_page: false
