theme: jekyll-theme-cayman
title: "Sarra BOUHENNI"
email: "sarra.bouhenni@liris.cnrs.fr"
address: "Villeurbanne, France"
description: "I am currently a PhD candidate interested in Distributed Graph Algorithms and Big Data."
github:
  is_project_page: false
