theme: jekyll-theme-cayman
title: "Sarra BOUHENNI"
description: "PhD candidate @ Laboratoire d'InfoRmatique en Image et Systems d'information (LIRIS), Université Claude Bernard Lyon 1, France"
email: "sarra.bouhenni@liris.cnrs.fr"
github:
  is_project_page: false
